#!/usr/bin/env php
<?php

require_once __DIR__ . '/MongoAdminKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new MongoAdminKernel('prod', true);

$application = new Application($kernel);
$application->run();

