app.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  templating: []

twig.config: ~

zend.config:
  logger:
    priority: 2
    path: %kernel.root_dir%/logs/%kernel.environment%.log

mongo_admin.config:
  servers:
    server_one: localhost:27017
    server_two: localhost:27017